Fix Rich Text Editor (RTE) for ALPS Highlight paragraph
adventistchurch/alps-gutenberg-blocks pull request #21
Opened 2020-02-24 08:23 UTC by sergsadovyi

Closes adventistchurch/alps-wordpress#325

2020-02-25 11:17 UTC, designerbrent requested changes
Looks good and work fairly well.

- **Text Alignment**: The center/left/right doesn't work. Please use/add the appropriate classes from the following: 
   - `u-text-align--left`
   - `u-text-align--center`
   - `u-text-align--right`
- **List**: Is it possible to include a list inside this block?

2020-03-02 14:27 UTC, sergsadovyi commented
> Text Alignment: The center/left/right doesn't work. Please use/add the appropriate classes from the following

Fixed

> List: Is it possible to include a list inside this block?

The List is a separate Gutenberg block. It is not common to have nested blocks in Gutenberg. But if it is a wanted feature, I can do more research how to add list functionality to paragraph block.

2020-03-05 16:11 UTC, designerbrent approved these changes

2020-03-05 16:12 UTC, designerbrent commented
This is good. Let's leave the lists for a later time, since that is a non-standard item. I'd rather not break the standard way of doing things in Wordpress, if we can help it.

2020-03-05 16:12 UTC, merged