feat: add version param to plugin script
adventistchurch/alps-gutenberg-blocks pull request #35
Opened 2020-07-24 14:39 UTC by sergsadovyi

2020-07-27 12:57 UTC, designerbrent requested changes
I'm not seeing any change currently, as it is still pulling this URL: `http://alpswp3.test:8888/wordpress5/wp-content/plugins/alps-gutenberg-blocks/dist/blocks.build.js?ver=1`

![2020-07-27 at 8 55 AM](https://user-images.githubusercontent.com/132864/88544308-3150df00-cfe7-11ea-9666-64ed10ccf2c8.png)

2020-07-27 15:01 UTC, sergsadovyi commented
Found the duplicated script enqueue

2020-07-27 22:23 UTC, designerbrent requested changes

2020-07-27 22:23 UTC, designerbrent commented on src/init.php
> -	);
This this function out, the edit pages crash. 

![2020-07-27 at 6 21 PM](https://user-images.githubusercontent.com/132864/88597826-1fe2f380-d036-11ea-9c96-0be90be0e2fe.png)

2020-07-27 22:23 UTC, designerbrent commented on src/init.php
> +        ALPS_GUTENBERG_VERSION,
Can you add this to the CSS scripts below?

2020-07-28 13:46 UTC, designerbrent commented
Closing this as it will be covered in #36.

2020-07-28 13:46 UTC, closed without merging