Blocks i18n
adventistchurch/alps-gutenberg-blocks pull request #36
Opened 2020-07-27 20:33 UTC by sergsadovyi

2020-07-27 22:30 UTC, designerbrent requested changes
From my initial testing, this looks good, with the exceptions of the changes noted above.

2020-07-27 22:30 UTC, designerbrent commented on composer.json
> +  "version": "1.5.1",
Will we need to update this on every new build? Can we pull this from the `kernl.version` file as part of a `npm build` script?

2020-07-27 22:30 UTC, designerbrent commented on package.json
> +  "version": "1.5.1",
Same question as above update updating this version number.

2020-07-27 22:30 UTC, designerbrent commented on plugin.php
> +define('ALPS_GUTENBERG_VERSION', '1.5.1');
Can this version number be pulled from the `kernl.version` file as part of the `npm build` script?

2020-07-28 13:45 UTC, designerbrent commented on src/init.php
> +		['wp-edit-blocks']
Make sure to include the version number for the styles.

2020-08-03 12:57 UTC, designerbrent commented
@sergsadovyi Is this PR ready to be fully reviewed?

2020-08-03 21:11 UTC, sergsadovyi commented
Not yet. Working on build process.

2020-08-31 13:24 UTC, designerbrent commented
@sergsadovyi When attempting to run the code, I get the following error: 

> Fatal error: Uncaught Error: Class 'ALPS\Gutenberg\Blocks\LatestPostsBlock' not found in /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-content/plugins/alps-gutenberg-blocks/src/init.php:47 Stack trace: #0 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-includes/class-wp-hook.php(287): alps_gutenberg_blocks_init('') #1 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-settings.php(540): do_action('init') #4 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-config.php(90): require_once('/Users/hardinge...') #5 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-load.php(37): require_once('/Users/hardinge...') #6 /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-blog-header.php(13): require_once('/Users/hardinge...') #7 /Users/ in /Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-content/plugins/alps-gutenberg-blocks/src/init.php on line 47

> There has been a critical error on your website.

I tried running `npm run dev` and got the following error: 

![2020-08-31 at 9 23 AM](https://user-images.githubusercontent.com/132864/91724739-c0fc2700-eb6b-11ea-933a-970ebe8f27c9.jpg)

> ./src/blocks/latest-posts/components/edit.js
> Module not found: Can't resolve '@wordpress/api-fetch' in '/Users/hardingeb/Sites/alps/alps-wordpress-3/wordpress5/wp-content/plugins/alps-gutenberg-blocks/src/blocks/latest-posts/components'

2020-08-31 21:27 UTC, designerbrent approved these changes
Looks good.

2020-08-31 21:28 UTC, merged