V3.62 design consistency on gutenberg blocks
adventistchurch/alps-gutenberg-blocks pull request #64
Opened 2021-04-28 10:21 UTC by YauheniKapliarchuk

@designerbrent 

Please review this PR.

Thanks

2021-05-03 16:07 UTC, designerbrent requested changes
## Accordion
### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Body: `Enter your Body Text...`



## Blockquote
### Control block: 
Please make sure the margin on the Extend Quote and Strong Quote controls have a left margin like the Paragraph block does.
![2021-05-03 at 10 33 AM](https://user-images.githubusercontent.com/132864/116889984-2886dc80-abfb-11eb-9bd8-111cf8bb1e7e.jpg)

## Content Block
Why does the `Link URL` have a block around it? the other input are all with an underline but the link has a box around it.
![2021-05-03 at 10 39 AM](https://user-images.githubusercontent.com/132864/116890711-e7db9300-abfb-11eb-86eb-6c1e14026a02.jpg)

### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Read More Button: `Default: Read More`
- Link URL: `https://...`


## Content Expand
Nothing has been done yet to this block.

## Content Show More
### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Description: `Enter your Description...`
- Body: `Enter your Body Text... (Displays on click for Show More button)
- 

## CTA 
### Card Title
Please change card title to `Call to Action (CTA)`. But keep the other references to CTA.

### Control block: 
Please make sure the margin on the Dark Background and Background Image controls have a left margin like the Paragraph block does.
![2021-05-03 at 11 01 AM](https://user-images.githubusercontent.com/132864/116893396-ea8bb780-abfe-11eb-8587-ed9565fc9c2a.jpg)

### Buttons: 
Reverse the order of the button fields, so it should start with the Text input on top followed by the URL input.

### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Description: `Enter your Description...`
- Body: `Enter your Body Text... (Displays on click for Show More button)
- Button 1 Text: `Button Label`
- Button 1 URL: `https://...`
- Button 2 Text: `Button Label`
- Button 2 URL: `https://...`
- Both open checkboxes: `Open link in a new window`

## Gallery
### Default View
Do we need to have the second "Gallery" title? 
![2021-05-03 at 11 06 AM](https://user-images.githubusercontent.com/132864/116894094-a6e57d80-abff-11eb-96fa-48a0c62ca262.jpg)

### Placeholder Text
Please change the placeholder text to the following:
- Gallery Title: `Enter your Gallery Title...`

## Highlighted Paragraph
### Placeholder Text
Please change the placeholder text to the following:
- Content: `Enter your Content...`

## Image (2UP)
### Default View
Do we need to have the second "Image (2UP)" title? 
![2021-05-03 at 11 08 AM](https://user-images.githubusercontent.com/132864/116894366-f75cdb00-abff-11eb-9d55-35017e7f489a.jpg)

### Images Selected
Only 1 image is showing on the admin side.
1. Selected 2 images
![2021-05-03 at 11 10 AM](https://user-images.githubusercontent.com/132864/116894566-3723c280-ac00-11eb-9b65-638307cb718e.jpg)
2. Only 1 shows.
![2021-05-03 at 11 11 AM](https://user-images.githubusercontent.com/132864/116894701-5cb0cc00-ac00-11eb-86c5-2b1741cfb752.jpg)

The description is just showing the HTML, not rendering it.

## Image Breakout
### Placeholder Text
Please change the placeholder text to the following:
- Caption: `Enter your Caption...`

## Inline Sidebar
### Placeholder Text
Please change the placeholder text to the following:
- Preface: `Enter your title Preface...`
- Title: `Enter your Title...`

## Latest Posts

### Posts with no images
If there are no images on a post, the width of the text should be 3 columns, not 2. The functionality of the block in the current release is working correct.
![2021-05-03 at 12 03 PM](https://user-images.githubusercontent.com/132864/116901372-d7c9b080-ac07-11eb-8aee-a06d220e39a6.jpg)


### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Link Label: Please change this title to `See All Link Label`
- Link Label: `Enter your link label...`
- See All URL: `https://...`

## Media Block
### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Description: `Enter your Description...`
- Category: `Enter your Categories...`
- Date: `Enter your Date...`

## Media Testimonies
### Placeholder Text
Please change the placeholder text to the following:
- Title: `Enter your Title...`
- Quote: `Enter your Quote...`
- Video: `Enter your Video title...`

2021-05-03 16:07 UTC, designerbrent commented on src/blocks/media-block/editor.scss
>        text-transform: uppercase;
Remove this line.

2021-05-03 16:07 UTC, designerbrent commented on src/blocks/media-block/editor.scss
>      &-meta__buttom {
This is misspelled. It should be spelled `__bottom` and needs to be corrected in all locations.

2021-05-03 16:07 UTC, designerbrent commented on src/blocks/media-block/components/MediaBlockEditComponent.js
> +                                <div className={"alps__media-block__text-section-meta__buttom"}>
Correct classname to `alps__media-block__text-section-meta__bottom`.

2021-05-03 16:07 UTC, designerbrent commented on src/blocks/media-block/components/MediaBlockEditComponent.js
> +                                    <div className={"alps__media-block__text-section-meta__buttom__category"}>
Correct classname to `alps__media-block__text-section-meta__bottom__category`

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +  font-family: Avenir;
Remove

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +  }
Add style: 
`opacity: 0.5;`

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-family: Avenir, normal;
Remove all `font-family` declarations.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    margin-left: 20px;
Switch to `0`.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    padding: 0 15px 0 15px;
Switch to `0 15px 0 0`

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-family: Avenir;
Remove all `font-family` declarations.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-family: Avenir;
Remove all `font-family` declarations.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-family: Avenir;
Remove all `font-family` declarations.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-family: Avenir;
Remove all `font-family` declarations.

2021-05-03 16:07 UTC, designerbrent commented on src/common.scss
> +    font-weight: 800;
Switch to `600`.

2021-05-03 16:07 UTC, designerbrent commented on src/blocks/image-breakout/style.scss
> +//}
Why is this getting commented out? This needs to be here to prevent gaps like this: 

![2021-05-03 at 11 59 AM](https://user-images.githubusercontent.com/132864/116900705-098e4780-ac07-11eb-8a77-7aa2ae3eadb7.jpg)

2021-05-04 14:44 UTC, designerbrent commented
A couple other items that came up on our call today that need to be addressed: 

- [ ] **Repeated Styles**: In the final rendered `.css`, all the styles are repeated several times. This needs to be fixed.
- [ ] **Rich text inputs**: If we can't control which fields have rich text controls, at least make the output work when they do. The button labels currently are outputting plain text, and showing the HTML, not rendering it.
- [ ] **Upload Button** Please change the color of the upload button to match the dark blue. You can use the lightblue on hover, if you want, but I want to see the button be the same as the other text labels.

2021-05-10 09:10 UTC, YauheniKapliarchuk commented on src/blocks/media-block/editor.scss
>        text-transform: uppercase;
It was removed

2021-05-10 09:12 UTC, YauheniKapliarchuk commented on src/blocks/media-block/editor.scss
>      &-meta__buttom {
I was fixed. Thanks

2021-05-10 09:13 UTC, YauheniKapliarchuk commented on src/blocks/media-block/components/MediaBlockEditComponent.js
> +                                <div className={"alps__media-block__text-section-meta__buttom"}>
It was fixed. Thanks

2021-05-10 09:13 UTC, YauheniKapliarchuk commented on src/blocks/media-block/components/MediaBlockEditComponent.js
> +                                    <div className={"alps__media-block__text-section-meta__buttom__category"}>
It was fixed. Thanks

2021-05-10 09:14 UTC, YauheniKapliarchuk commented on src/common.scss
> +  font-family: Avenir;
It was fixed. Thanks

2021-05-10 09:17 UTC, YauheniKapliarchuk commented on src/common.scss
> +  }
It was fixed. Thanks

2021-05-10 09:19 UTC, YauheniKapliarchuk commented on src/common.scss
> +    padding: 0 15px 0 15px;
It was fixed. Thanks

2021-05-10 09:19 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-weight: 800;
It was fixed. Thanks

2021-05-10 09:20 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-family: Avenir, normal;
It was fixed. Thanks

2021-05-10 09:20 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-family: Avenir;
It was fixed. Thanks

2021-05-10 09:20 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-family: Avenir;
It was fixed. Thanks

2021-05-10 09:21 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-family: Avenir;
It was fixed. Thanks

2021-05-10 09:21 UTC, YauheniKapliarchuk commented on src/common.scss
> +    font-family: Avenir;
It was fixed. Thanks

2021-05-10 09:37 UTC, YauheniKapliarchuk commented on src/common.scss
> +    margin-left: 20px;
It was fixed. Thanks

2021-05-10 09:49 UTC, YauheniKapliarchuk commented on src/blocks/image-breakout/style.scss
> +//}
It was fixed. Thanks

2021-05-10 23:41 UTC, designerbrent requested changes
## Items to Address


Here are my comments regarding the pull request. While a lot of the placeholder text was done, many of the other items were not addressed. Please addressed the individual check boxes for each block.

## Global Items: 

- [ ] **Upload Image** button: Edit the colors to match the blue of the headlines.  ![2021-05-10 at 7 18 PM](https://user-images.githubusercontent.com/132864/117735976-95364400-b1c4-11eb-9057-2a23cb576e9a.jpg)


## Blockquote

- [ ] Please make sure the margin on the Extend Quote and Strong Quote controls have a left margin like the Paragraph block does. ![2021-05-03 at 10 33 AM](https://user-images.githubusercontent.com/132864/116889984-2886dc80-abfb-11eb-9bd8-111cf8bb1e7e.jpg)

## Content Block
- [ ] Can you disable the editor blocks for the button fields? ![2021-05-10 at 7 15 PM](https://user-images.githubusercontent.com/132864/117735786-3375da00-b1c4-11eb-9745-56861805d9cc.jpg)

## Content Expand

- [ ] Please finish upgrading this block. This one has been around longer and needs to be upgraded.

## Content Show More
- [x] The `x` button is missing from the image to remove it. ![2021-05-10 at 7 21 PM](https://user-images.githubusercontent.com/132864/117736192-15f54000-b1c5-11eb-968f-a05625b6e86f.jpg)


## Call to Action (CTA)
- [ ] **Title:** Please change card title to `Call to Action (CTA).` But keep the other references to `CTA`. (I want to make sure the existing blocks still work.)
- [ ] **Control Block:** Please make sure the margin on the Dark Background and Background Image controls have a left margin like the Paragraph block does. ![2021-05-03 at 11 01 AM](https://user-images.githubusercontent.com/132864/116893396-ea8bb780-abfe-11eb-8587-ed9565fc9c2a.jpg)

## Image (2UP)
- [ ] Negative margin should **ONLY** apply on the front side, not the edit side. ![2021-05-10 at 7 25 PM](https://user-images.githubusercontent.com/132864/117736444-97e56900-b1c5-11eb-8d8a-a6128db366f7.jpg)
- [ ] Negative Margin on the front shouldn't start at `701px`, not `1301px`

## Image: Breakout
- [ ] Negative margin is not applying from `701px` and wider. ![2021-05-10 at 7 37 PM](https://user-images.githubusercontent.com/132864/117737138-345c3b00-b1c7-11eb-8ca1-b2bac749d5f2.jpg)

## Inline Block
- [ ] Since this block is a duplicate of the `Content Expand` block, please remove this from the code.


<hr /> 

# Completion List

(please don't check off the items, as I will do that as I'm done reviewing each item.)

- [x] Accordion
- [ ] Blockquote
- [ ] Content Block
- [ ] Content Expand
- [ ] Content Show More
- [ ] CTA 
- [x] Gallery
- [ ] Highlighted Paragraph
- [ ] Image (2UP)
- [ ] Image Breakout
- [ ] Inline Sidebar
- [x] Latest Posts
- [x] Media Block
- [x] Media Testimonies

2021-05-11 20:30 UTC, designerbrent requested changes
Just a few more changes that go missed: 

## Global Items: 

- [x] Upload Image button: Edit the colors to match the blue of the headlines. ![2021-05-11 at 4 26 PM](https://user-images.githubusercontent.com/132864/117880080-b0ad5780-b275-11eb-9d10-fa977b032ebb.jpg)

## Content Block

- [ ] When HTML is used in the **Read More** button, the HTML and content is stripped. Please remove the HTML only, not that content inside the markup.

## Content Expand
- [x] The backend works fine, but on the frontend, the Title doesn't show and the Body is pulling content from somewhere else.

2021-05-11 21:02 UTC, designerbrent commented
## Inline Sidebar:

- [ ] Please remove the reference to the Inline Sidebar so the block will compile. https://github.com/adventistchurch/alps-gutenberg-blocks/blob/ce127982d7ae83f1e95fed69030c9b178a6cffd3/src/blocks.js#L22

2021-05-17 10:44 UTC, designerbrent approved these changes
I see that you found a way to disable the bold, italic, etc for the buttons. 👏 

💯

2021-05-17 10:44 UTC, merged